import { AuthUser } from '../types';

export const DEMO_USERS: Record<string, AuthUser & { passwordHash: string }> = {
  'receptionist@demo.hospital': {
    id: 'user-rec-01',
    name: 'Sarah Thomas',
    email: 'receptionist@demo.hospital',
    role: 'receptionist',
    staffId: 'REC-104',
    department: 'Front Desk',
    avatarColor: 'bg-blue-600',
    phone: '+1 (555) 234-5678',
    shiftHours: '08:00 AM - 04:00 PM',
    lastLogin: 'Just now',
    passwordHash: 'Demo@123',
  },
  'doctor@demo.hospital': {
    id: 'user-doc-01',
    name: 'Dr. Anu',
    email: 'doctor@demo.hospital',
    role: 'doctor',
    staffId: 'DOC-201',
    department: 'Dentistry',
    doctorId: 'doc-1',
    avatarColor: 'bg-emerald-600',
    phone: '+1 (555) 876-5432',
    shiftHours: '09:00 AM - 05:00 PM',
    lastLogin: 'Today, 08:30 AM',
    passwordHash: 'Demo@123',
  },
  'admin@demo.hospital': {
    id: 'user-adm-01',
    name: 'Hospital Admin',
    email: 'admin@demo.hospital',
    role: 'admin',
    staffId: 'ADM-001',
    department: 'Administration',
    avatarColor: 'bg-purple-600',
    phone: '+1 (555) 999-0000',
    shiftHours: '24/7 System Admin',
    lastLogin: 'Today, 07:15 AM',
    passwordHash: 'Demo@123',
  },
};

export const DEMO_CREDENTIALS_LIST = [
  {
    roleName: 'Receptionist',
    role: 'receptionist' as const,
    name: 'Sarah Thomas',
    department: 'Front Desk',
    email: 'receptionist@demo.hospital',
    password: 'Demo@123',
    badgeColor: 'bg-blue-100 text-blue-800 border-blue-200',
    description: 'Registers patients, assigns doctors, and issues OP tokens.',
  },
  {
    roleName: 'Doctor',
    role: 'doctor' as const,
    name: 'Dr. Anu',
    department: 'Dentistry',
    email: 'doctor@demo.hospital',
    password: 'Demo@123',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    description: 'Views assigned patient queue, patient status, and schedule.',
  },
  {
    roleName: 'Admin',
    role: 'admin' as const,
    name: 'Hospital Admin',
    department: 'Administration',
    email: 'admin@demo.hospital',
    password: 'Demo@123',
    badgeColor: 'bg-purple-100 text-purple-800 border-purple-200',
    description: 'Manages staff users, doctor roster, departments, and reports.',
  },
];
